config/routes.rb
RegistroTBRails3::Application.routes.draw do

  #get "start_controller/index"
  get 'inicio' => 'start_controller#index', as: 'inicio'
  resources :registros
  devise_for :users

  root to: 'registros#index'

  devise_for :users, :path_prefix => 'my'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      #El admin somos nosotros
      #No capturamos solamente vemos resultados
      can :view_all
    else
      can :fill_form
    end
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  attr_accessible :institution
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
  attr_accessible :nationality
end

app/models/posgrado.rb
class Posgrado < ActiveRecord::Base
  attr_accessible :posgrado
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  attr_accessible :profession
end

app/models/registro.rb
class Registro < ActiveRecord::Base

  belongs_to :state
  attr_accessible :apellido_materno, :apellido_paterno, :email, :nationality_id, :nombre, :posgrado_id, :profession_id, :rfc, :workshop_id, :no_deposito_cuenta_bancaria,:state_id, :hospital_general, :service_id, :institution_id, :attendance, :user_id, :otro

  validates_presence_of :nombre, :apellido_paterno, :apellido_materno, :rfc, :email, :nationality_id, :profession_id, :no_deposito_cuenta_bancaria, :message => "No puede ir vacio"


  def self.usuario_actual (user_id)
    Registro.where("user_id = ?", user_id)
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :service
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :registros
  attr_accessible :state
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :timeoutable, :timeout_in => 15.minutes
  rolify
  rolify :before_add => :before_add_method

  def before_add_method(role)
    # do something before it gets added
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  attr_accessible :workshop

  def self.decrement_attendance(taller_id)
    Workshop.find(taller_id).decrement!(:cupo,1)
  end

  def self.availability_of_group
    @wk = Workshop.where("cupo > 0").all

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  # GET /registros
  # GET /registros.json
  before_filter :authenticate_user!
  def index

      if   can? :view_all, @user
        @registros = Registro.all
      else

         @registros = Registro.usuario_actual(current_user.id)
      end

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @registros }
      end

    end


  # GET /registros/1
  # GET /registros/1.json
  def show
    @registro = Registro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registro }
    end
  end

  # GET /registros/new
  # GET /registros/new.json
  def new
    @registro = Registro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registro }
    end
  end

  # GET /registros/1/edit
  def edit
    @registro = Registro.find(params[:id])
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(params[:registro])

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro exitoso.' }
        format.json { render json: @registro, status: :created, location: @registro }
        Workshop.decrement_attendance(@registro.workshop_id)

      else
        format.html { render action: "new" }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registros/1
  # PUT /registros/1.json
  def update
    @registro = Registro.find(params[:id])

    respond_to do |format|
      if @registro.update_attributes(params[:registro])
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro = Registro.find(params[:id])
    @registro.destroy

    respond_to do |format|
      format.html { redirect_to registros_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/start_controller_controller.rb
class StartControllerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/start_controller_helper.rb
module StartControllerHelper
end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="text-center"></div>
   <footer class="footer">
    <nav>
      <ul>
        <% if user_signed_in? %>
            <p>Hola <%= current_user.email %>.</p>
        <% end %>
      </ul>
    </nav>
  </footer> 
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Registro al XIX Curso de actualización</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


          <ul class="nav navbar-nav navbar-right">

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sesión <b class="caret"></b></a>
              <ul class="dropdown-menu">

                <% if user_signed_in? %>
                    <li> <%= link_to "Cerrar sesión",destroy_user_session_path, :method => :delete, :class => "navbar-letras-salud" %></li>
                <% else %>
                    <li><%= link_to "Ingresa", new_user_session_path,:class => "navbar-letras-salud" %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

<% else %>


    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Registro al XIX curso de actualización</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">



        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secretaría de Salud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<%= render 'layouts/header' %>

<body class="pull_top">

<div class="container">
  <%= yield %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/registros/_form.html.erb
<%= form_for @registro, :validate => true do |f| %>
  <% if @registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registro.errors.count, "errores") %> Se presentaron los siguientes errores:</h2>

      <ul>
      <% @registro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido_paterno %><br />
    <%= f.text_field :apellido_paterno %>
  </div>
  <div class="field">
    <%= f.label :apellido_materno %><br />
    <%= f.text_field :apellido_materno %>
  </div>
  <div class="field">
    <%= f.label "Correo Electrónico" %><br />
    <%= f.text_field :email, :value => current_user.email, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label "Registro Federal de Contribuyentes (RFC)" %><br />
    <%= f.text_field :rfc %>
  </div>
  <div class="field">
    <% @paises = Nationality.all %>
    <%= f.label "País de origen" %><br />
    <%= f.select :nationality_id, @paises.collect{ |e| [e.nationality, e.id] }%>
  </div>
  <div class="field">

    <% @profesion = Profession.all %>
    <%= f.label "Profesión" %><br />
    <%= f.select :profession_id, @profesion.collect{ |e| [e.profession, e.id] }%>

  </div>
  <div class="field">
    <% @posgrado = Posgrado.all %>
    <%= f.label "Posgrado" %><br />
    <%= f.select :posgrado_id, @posgrado.collect{ |e| [e.posgrado, e.id] }%>
  </div>

    <div class="field">
      <% @workshop = Workshop.availability_of_group %>
      <%= f.label "Talleres" %><br />
      <%= f.select :workshop_id, @workshop.collect{ |e| [e.workshop, e.id] }%>
    </div>

    <div class="field">
      <%= f.label "Número de deposito en cuenta bancaria" %><br />
      <%= f.text_field :no_deposito_cuenta_bancaria %>
    </div>

    <div class="field">
      <% @state = State.all %>
      <%= f.label "Estado" %><br />
      <%= f.select :state_id, @state.collect{ |e| [e.state, e.id] }%>
    </div>



    <div class="field">
      <%= f.label "Es personal del hospital general" %><br />
      <%= f.select :hospital_general, options_for_select([
                                                         ["No", "false"],
                                                         ["Si", "true"]

                                                 ]),{}, :onchange => "test();" %>

    </div>

    <div class="field" style="display: none;" id="div_servicio_id">
      <% @service = Service.all %>
      <%= f.label "En qué servicio" %><br />
      <%= f.select :service_id, @service.collect{ |e| [e.service, e.id] }, :style=>"display:none", :html => { :class => "class_name_here"}%>
    </div>

    <div class="field">
      <%= f.label :otro, "Si es otro especifique" %>
      <%= f.text_field :otro %>
    </div>


    <div class="field">
      <% @inst = Institution.all %>
      <%= f.label "Institución" %><br />
      <%= f.select :institution_id, @inst.collect{ |e| [e.institution, e.id] }%>
    </div>




    <div class="field">
      <%= f.label "¿Ha asistido anteriormente a este curso?" %><br />
      <%= f.select :attendance, options_for_select([
                                                                 ["Si", "true"],
                                                                 ["No", "false"]

                                                         ]) %>
      <br>
      <br>

    </div>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id, :readonly => true  %>
    </div>


  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/registros/edit.html.erb
<h1>Editing registro</h1>

<%= render 'form' %>

<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>

app/views/registros/index.html.erb
<h1>Mi registro al taller</h1>

<table class="table">
  <tr>
    <th>Nombre</th>
    <th>Apellido paterno</th>
    <th>Apellido materno</th>
    <th>Email</th>
    <th>RFC</th>
    <th>País de origen</th>
    <th>Profesión</th>
    <th>Posgrado</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registros.each do |registro| %>
  <tr>
    <td><%= registro.nombre %></td>
    <td><%= registro.apellido_paterno %></td>
    <td><%= registro.apellido_materno %></td>
    <td><%= registro.email %></td>
    <td><%= registro.rfc %></td>
    <td><%= Nationality.select("nationality").where("id = ?", registro.nationality_id).to_a.map(&:nationality).join("") %></td>
    <td><%= Profession.select("profession").where("id=?", registro.profession_id).to_a.map(&:profession).join("") %></td>
    <td><%= Posgrado.select("posgrado").where("id=?", registro.posgrado_id).to_a.map(&:posgrado).join("") %></td>



<% if   can? :view_all, @user %>
    <td><%= link_to 'Mostrar', registro %></td>
    <td><%= link_to 'Editar', edit_registro_path(registro) %></td>
    <td><%= link_to 'Eliminar', registro, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
<%else%>
    <td><%= link_to 'Mostrar', registro %></td>
    <td><%= link_to 'Descargar gafete', asset_path("Gafete.pdf") %></td>
<%end%>
  </tr>
<% end %>
</table>

<br />

<% if   can? :view_all, @user %>
    <%= link_to 'Agrega tu registro', new_registro_path %>
<%else%>
    <% if @registros.blank? %>
    <%= link_to 'Agrega tu registro', new_registro_path %>
    <%else%>
    <p>Gracias por tu registro</p>
    <%end%>
<%end%>


<div class="row">
  <div class="md-col-12">
    <h2>Instrucciones para inscripción:</h2>
  	<h3>Estimado Participante:</h3>

<p>Con la finalidad de brindarte mayor comodidad, la inscripción para este curso será EXCLUSIVAMENTE VIA INTERNET.  Para poder inscribirte deberás realizar previamente el donativo de $500.00 a la siguiente cuenta
Banamex: sucursal 233, cuenta 1439889, a nombre de Comité Nacional de Lucha Contra la Tuberculosis.</p>
<ul>
  <li><p class="text-center">
    <%= image_tag("voucher.jpg",size:"441x541", :alt => "logo.jpg") %>
  </p></li>
  <li>1.-Debe contar con comprobante de depósito para realizar el proceso de registro.</li>
  <li>2.-Ingrese los datos que se solicitan y tome en cuenta que  aparecerán en su constancia de participación (con valor curricular), tal y como los ingrese al sistema.</li>
  <li>3.-Los talleres tienen cupo limitado, así se sugiere realice su inscripción lo antes posible.</li>
  <li>4.- Después de dar click en “enviar datos” deberá descargar e imprimir el formato de inscripción del Hospital General México con sus datos y el gafete que le permitirá el acceso al Hospital (no podrás accesar sin él).
El primer día del evento deberá entregar el formato de registro con sus datos,  firmado y una fotocopia de éste, junto con la ficha de depósito, los cuales podrá canjear por su paquete de material didáctico</li>
</ul>

<p>Si tiene alguna duda por favor escribe a: micobacnal@gmail.com</p>
  </div>
</div>

app/views/registros/new.html.erb
<h1>Ingresa tus datos</h1>

<%= render 'form' %>

<%= link_to 'Volver', registros_path %>

app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id de registro:</b>
  <%= @registro.id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @registro.nombre %>
</p>

<p>
  <b>Apellido paterno:</b>
  <%= @registro.apellido_paterno %>
</p>

<p>
  <b>Apellido materno:</b>
  <%= @registro.apellido_materno %>
</p>

<p>
  <b>Email:</b>
  <%= @registro.email %>
</p>

<p>
  <b>Rfc:</b>
  <%= @registro.rfc %>
</p>

<p>
  <b>País de origen:</b>
  
  <%= Nationality.select("nationality").where("id = ?", @registro.nationality_id).to_a.map(&:nationality).join("") %>
</p>

<p>
  <b>Estado de procedencia:</b>
  
  <%= State.select("state").where("id = ?", @registro.state_id).to_a.map(&:state).join("") %>
</p>

<p>
  <b>Profesión:</b>
  <%= Profession.select("profession").where("id=?", @registro.profession_id).to_a.map(&:profession).join("") %>
</p>

<p>
  <b>Posgrado:</b>
  <%= Posgrado.select("posgrado").where("id=?", @registro.posgrado_id).to_a.map(&:posgrado).join("")%>
</p>

<p>
  <b>Taller:</b>
  <%= Workshop.select("workshop").where("id=?", @registro.workshop_id).to_a.map(&:workshop).join("")%>
</p>

<p>
  <b>Institución:</b>
  <%= Institution.select("institution").where("id=?", @registro.institution_id).to_a.map(&:institution).join("")%>
</p>

<% if   can? :view_all, @user %>
   <%= link_to 'Editar', edit_registro_path(@registro) %> |
<%= link_to 'Volver', registros_path %>
<%else%>
 
<%= link_to 'Volver', registros_path %>  
<%end%>

app/views/start_controller/index.html.erb
<div class="jumbotron">
  <h3>XVIII Curso Actualización en el Diagnóstico y Tratamiento de la
    Tuberculosis en el Niño y el Adulto</h3>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
</div>